-- insert into employee (FIRST_NAME, LAST_NAME, EMAIL_ID) values ('Nguyen','Trung Hieu', 'hieunt@gmail.com');
-- insert into employee (FIRST_NAME, LAST_NAME, EMAIL_ID) values ('Nguyen','Van Manh', 'manhnv@gmail.com');
-- insert into employee (FIRST_NAME, LAST_NAME, EMAIL_ID) values ('Nguyen','van A ', 'anv@gmail.com');